VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CompanyData"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public CompanyName As String
Public UpgradedBy As String
Public Description As String
Public ScaleNotes As String
Public GrowthNotes As String
Public ProfitabilityNotes As String
Public RevenueModelNotes As String
Public OwnershipDynamicNotes As String
Public ConcentrationsNotes As String
Public CompanyOwner As String
Public Team As String
Public ProspectSource As String
Public SplitCredit As String
Public Website As String
Public HQ As String
Public Employees As String
Public LatestRaisedDate As String
Public LatestRaised As String
Public TotalRaised As String
